GET http://localhost:6969

###

POST http://localhost:6969/clients
Content-Type: application/json

{
    "name": "Manicia Theron",
    "email": "manicia@gmail.com",
    "contact": "0663506848",
    "password": "password"
}
